AppLib/CE.ReportPortalWeb/Models/Logins.cs
using System.Web.Mvc;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using CE.ReportPortalWeb.Common;

namespace CE.ReportPortalWeb.Models
{
    public class Logins
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        [Required(ErrorMessage = "User Name is Required")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        public string Password { get; set; }

        public int EnvID { get; set; }

        public bool Enabled { get; set; }

        public int ClientID { get; set; }
        
        public string UserType { get; set;}
       
        public string Client { get; set; }

        public List<SelectListItem> ClientList { get; set; }
    }
}

AppLib/CE.ReportPortalWeb/Models/ReportViewModel.cs
using Microsoft.PowerBI.Api.V1.Models;

namespace CE.ReportPortalWeb.Models
{
    public class ReportViewModel
    {
        public Report Report { get; set; }

        public string AccessToken { get; set; }
    }
}

AppLib/CE.ReportPortalWeb/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.PowerBI.Api.V1;
using Microsoft.PowerBI.Security;
using Microsoft.Rest;
using CE.ReportPortalWeb.Common;
using CE.ReportPortalWeb.Common.QueryStringEncryptor;
using CE.ReportPortalWeb.Models;

namespace CE.ReportPortalWeb.Controllers
{
    public class DashboardController : Controller
    {
        private readonly string _workspaceCollection;
        private string _workspaceId;
        private readonly string _accessKey;
        private readonly string _apiUrl;
        private readonly byte _envID;

        public DashboardController()
        {
            _workspaceCollection = ConfigurationManager.AppSettings["powerbi:WorkspaceCollection"];
            //_workspaceId = ConfigurationManager.AppSettings["powerbi:WorkspaceId"];
            _accessKey = ConfigurationManager.AppSettings["powerbi:AccessKey"];
            _apiUrl = ConfigurationManager.AppSettings["powerbi:ApiUrl"];
            _envID=Helpers.GetCurrentEnvironment();
        }

        public ActionResult Index()
        {
            if (Session[Constants.USER_SESSION_VARIABLE] == null)
            {
                Session.Abandon();
                return View("~/Views/Login/Index.cshtml");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Logout()
        {
            Session.Abandon();
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult Reports()
        {
            if (Session[Constants.USER_SESSION_VARIABLE] == null)
            {
                return View("~/Views/Login/Index.cshtml");
            }
            var cliId = ((UserSessionVariables) Session[Constants.USER_SESSION_VARIABLE]).clientID; //Request["clientId"];
            var clientId=Int32.Parse(cliId);
            using (var ent = new InsightsEntities())
            {
                ent.Database.Connection.Open();
                string pbiWorkspaceId;
                //Get workspace ID according to the environment and client ID
                if (_envID==0)
                {
                     pbiWorkspaceId = (from u in ent.PowerBIPortalClients
                                          where u.ClientID == clientId && u.EnvID==0
                                          select u.PBIWorkspaceID).FirstOrDefault();
                }
                else
                {
                     pbiWorkspaceId = (from u in ent.PowerBIPortalClients
                                          where u.ClientID == clientId && (u.EnvID==1 || u.EnvID==2 || u.EnvID==3 || u.EnvID==4)
                                          select u.PBIWorkspaceID).FirstOrDefault();
                }
                _workspaceId = pbiWorkspaceId;
                ent.Database.Connection.Close();
            }
            //Retrieve all the reports under the user's client ID
            using (var client = CreatePowerBiClient())
            {
                try
                {
                    var reportsResponse = client.Reports.GetReports(_workspaceCollection, _workspaceId);
                    var reportsList = new List<ReportDetails>();

                    foreach (var rep in reportsResponse.Value.ToList())
                    {
                        var repDetvar = new ReportDetails();
                        repDetvar.Reports = rep;
                        repDetvar.encDetails = QueryStringModule.Encrypt("reportId=" + rep.Id + "&clientId=" + clientId);
                        reportsList.Add(repDetvar);
                    }

                    var viewModel = new ReportsViewModel
                    {
                        ReportsDetails = reportsList
                    };

                    return PartialView(viewModel);
                }
                catch (Exception)
                {

                    return PartialView();
                }
                
            }
            
        }

        private string ExtractString(string mainStr,string key,string end)
        {
            var startindex = mainStr.IndexOf(key) + 9;
            if (end!="")
            {
                var substring = mainStr.Substring(startindex);
                var endindex = substring.IndexOf("&");
                return substring.Substring(0, endindex);
            }
            return mainStr.Substring(startindex);
        }

        //Embed report through the report ID and client ID
        public async Task<ActionResult> Report(string enc)
        {
            if (Session[Constants.USER_SESSION_VARIABLE] == null)
            {
                Session.Abandon();
                return View("~/Views/Login/Index.cshtml");
            }
            string dec = QueryStringModule.Decrypt(enc);
            var reportId = ExtractString(dec, "reportId=","&");
            var clientId = ExtractString(dec, "clientId=","");
            var cliId = Int32.Parse(clientId);
            using (var ent = new InsightsEntities())
            {
                ent.Database.Connection.Open();
                var pbiWorkspaceId = (from u in ent.PowerBIPortalClients
                                      where u.ClientID == cliId
                                      select u.PBIWorkspaceID).FirstOrDefault();
                _workspaceId = pbiWorkspaceId;
               
            }
            
            using (var client = CreatePowerBiClient())
            {
                var reportsResponse = await client.Reports.GetReportsAsync(_workspaceCollection, _workspaceId);
                var report = reportsResponse.Value.FirstOrDefault(r => r.Id == reportId);
                if (report != null)
                {
                    var embedToken = PowerBIToken.CreateReportEmbedToken(_workspaceCollection, _workspaceId, report.Id);

                    var viewModel = new ReportViewModel
                    {
                        Report = report,
                        AccessToken = embedToken.Generate(_accessKey)
                    };

                    return View(viewModel);
                }
            }
            return View();
        }
        
        private IPowerBIClient CreatePowerBiClient()
        {
            var credentials = new TokenCredentials(_accessKey, "AppKey");
            var client = new PowerBIClient(credentials)
            {
                BaseUri = new Uri(_apiUrl)
            };

            return client;
        }
    }
}

AppLib/CE.ReportPortalWeb/Controllers/LoginController.cs
using CE.ReportPortalWeb.Common;
using CE.ReportPortalWeb.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace CE.ReportPortalWeb.Controllers
{
    public class LoginController : Controller
    {
        private const string AppSetting_CEEnvironment = "CEEnvironment";

        // GET: Login
        public ActionResult Index()
        {
            ViewData["CEEnvironment"] = ConfigurationManager.AppSettings.Get(AppSetting_CEEnvironment);

            return View();
        }


        [HttpPost]
        public JsonResult CheckUser(string user, string password, string clientId)
        {
            if (user.Length == 0 && password.Length == 0 && clientId.Length == 0)
            {
                return Json("false_Please enter all details.", JsonRequestBehavior.AllowGet);
            }
            if (user.Length == 0 && password.Length == 0)
            {
                return Json("false_Please enter the username and password.", JsonRequestBehavior.AllowGet);
            }
            if (password.Length == 0 && clientId.Length == 0)
            {
                return Json("false_Please enter the password and Client ID.", JsonRequestBehavior.AllowGet);
            }
            if (clientId.Length == 0 && user.Length == 0)
            {
                return Json("false_Please enter the username and client ID.", JsonRequestBehavior.AllowGet);
            }
            if (user.Length == 0)
            {
                return Json("false_Please enter the username.", JsonRequestBehavior.AllowGet);
            }
            if (password.Length == 0)
            {
                return Json("false_Please enter the password.", JsonRequestBehavior.AllowGet);
            }
            if (clientId.Length == 0)
            {
                return Json("false_Please enter the client ID.", JsonRequestBehavior.AllowGet);
            }
            if (!clientId.All(char.IsDigit))
            {
                return Json("false_Please enter valid client ID",JsonRequestBehavior.AllowGet);
            }
            var environmentID = Convert.ToInt32(Helpers.GetCurrentEnvironment());
            var cliID = Convert.ToInt32(clientId);
            using (var ent = new InsightsEntities())
            {
                ent.Database.Connection.Open();
                PowerBIPortalLogin loginUser;
                //For production
                if (environmentID == 0)
                {
                    var loginUsers = (from u in ent.PowerBIPortalLogins
                        where u.Username == user && u.EnvID == environmentID
                        select u).GetEnumerator();
                    loginUsers.MoveNext();
                    loginUser = loginUsers.Current;
                    do
                    {
                        if (loginUsers.Current!=null && loginUsers.Current.ClientID == cliID)
                        {
                            loginUser = loginUsers.Current;
                        }
                    } while (loginUsers.MoveNext());
                    if (loginUser == null)
                    {
                        return Json("false_User does not exist", JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    var loginUsers = (from u in ent.PowerBIPortalLogins
                                      where u.Username == user
                                      select u).GetEnumerator();
                    loginUsers.MoveNext();
                    loginUser = loginUsers.Current;
                    do
                    {
                        if (loginUsers.Current != null && loginUsers.Current.ClientID == cliID)
                        {
                            loginUser = loginUsers.Current;
                        }
                    } while (loginUsers.MoveNext());
                    
                    if (loginUser == null)
                    {
                        return Json("false_User does not exist", JsonRequestBehavior.AllowGet);
                    }
                    if (loginUser.EnvID==0)
                    {
                        return Json("false_Cannot login to non-production environment with production user",
                            JsonRequestBehavior.AllowGet);
                    }
                }
                
                if (loginUser.Enabled != null && (loginUser.Enabled.Value == false))
                {
                    return Json("false_Disabled user", JsonRequestBehavior.AllowGet);
                }
                if (loginUser.UserType.ToLower()=="admin")
                {
                    var clientsList = (from c in ent.PowerBIPortalClients orderby c.ClientID select c.ClientID).ToList();
                    var valid = false;
                    foreach (var client in clientsList)
                    {
                        if (cliID==client)
                        {
                            valid = true;
                        }
                    }
                    if (!valid)
                    {
                        return Json("false_Invalid Client ID",JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    if (loginUser.ClientID!=cliID)
                    {
                        return Json("false_Invalid Client ID",JsonRequestBehavior.AllowGet);
                    }
                }
                
                ent.Database.Connection.Close();
                var encryptor = new Encryptor(password);
                if (!encryptor.VerifyHash(password, loginUser.PasswordSalt, loginUser.PasswordHash))
                {
                    return Json("false_Bad username/password", JsonRequestBehavior.AllowGet);
                }

                
                    var usv = new UserSessionVariables
                    {
                        clientID = clientId,
                        UserName = user,
                        UserType = loginUser.UserType
                    };

                    Session[Constants.USER_SESSION_VARIABLE] = usv;
                
                return Json(clientId, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Create()
        {
            if (Session[Constants.USER_SESSION_VARIABLE] == null)
            {
                return View("Index");
            }
            //populate client IDs
            var user=new Logins();
            user.ClientList = PopulateClientList();
            return View(user);
        }

        private List<SelectListItem> PopulateClientList()
        {
            using (var ent = new InsightsEntities())
            {
                ent.Database.Connection.Open();
                var clients = (from c in ent.PowerBIPortalClients orderby c.ClientID select c.ClientID).ToList();
                var clientsList = new List<SelectListItem>();
                foreach (var t in clients)
                {
                    clientsList.Add(new SelectListItem {Value = t.ToString(), Text = t.ToString()});

                }
                return clientsList;
            }
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return View("Index");
        }

        // POST: 
        [HttpPost]
        public ActionResult Create(Logins login)
        {
            if (Session[Constants.USER_SESSION_VARIABLE] == null)
            {
                return View("Index");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    using (var ent = new InsightsEntities())
                    {
                        
                        //Check if login exists
                        var lList = (from c in ent.PowerBIPortalLogins
                            where c.Username == login.UserName && c.ClientID == login.ClientID && c.EnvID == login.EnvID
                            select c.Username).ToList();
                        if (lList.Count > 0)
                        {
                            ModelState.AddModelError("UserName", "Duplicate Username");
                            //return Json("false", JsonRequestBehavior.AllowGet);
                            var user1 = new Logins();
                            user1.ClientList = PopulateClientList();
                            return View(user1);

                        }
                        //check for usertype
                        var userType = "user";
                        if (login.UserType == "true")
                        {
                            userType = "admin";
                        }
                        login.Enabled = true;
                        //Create login account
                        var newUserEnvID = (byte) login.EnvID;
                        var pbil = new PowerBIPortalLogin
                        {
                            Username = login.UserName,
                            FirstName = login.FirstName,
                            LastName = login.LastName,
                            ClientID = login.ClientID,
                            EnvID = newUserEnvID,
                            UpdateDate = DateTime.Now,
                            UserType = userType,
                            Enabled = true
                        };

                        //Encrypt password by hashing and using salt
                        var encryptor = new Encryptor("xv");
                        var bytes = new byte[16];
                        using (var rng = new System.Security.Cryptography.RNGCryptoServiceProvider())
                        {
                            rng.GetBytes(bytes);
                        }

                        // and if you need it as a string...

AppLib/CE.ReportPortalWeb/Views/Shared/Reports.cshtml
@using System.Diagnostics
@using Microsoft.PowerBI.Api.V1.Models
@model ReportsViewModel
@{
    Layout = null;

    var classNames = "panel panel-default dropdown";

    if (this.Request.Path.IndexOf("Report") > -1)
    {
        classNames += " active";
    }
}

<li class="@classNames">
    <a data-toggle="collapse" href="#reports-nav">
        <span class="icon fa fa-bar-chart"></span><span class="title">Reports</span>
    </a>
    <!-- Dropdown level 1 -->
    <div id="reports-nav" class="panel-collapse collapse">
        <div class="panel-body">
            <ul class="nav navbar-nav">

                @if (Model!=null && Model.ReportsDetails.Count!=0)
                {
                    foreach (var report in Model.ReportsDetails)
                    {
                        //var reportClass = Request.QueryString["reportId"] == report.Id ? "active" : "";
                        //var clientId = Request.QueryString["clientId"];
                        <li class="@report.Reports.Name">
                            @*@Html.ActionLink(report.Name, "Report", new { reportId = report.Id, clientId = clientId })*@
                            @Html.ActionLink(report.Reports.Name, "Report", new { enc = report.encDetails })
                        </li>
                    }

                }
                else
                {
                    <li class="">
                        <a>No Reports</a>
                    </li>
                }
             </ul>
        </div>
    </div>
</li>

AppLib/CE.ReportPortalWeb/Views/Shared/_Layout.cshtml
@using CE.ReportPortalWeb.Common
<!DOCTYPE html>
<html>
<head>
    <title>Aclara</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
    <!-- CSS Libs -->
    <link rel="stylesheet" type="text/css" href="~/lib/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/animate.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/bootstrap-switch.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/checkbox3.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/dataTables.bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/lib/css/select2.min.css">
    <!-- CSS App -->
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/themes/flat-blue.css">
    <link href="~/Content/powerbi.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body class="flat-blue">
    <div class="app-container">
        <div class="row content-container">
            <nav class="navbar navbar-default navbar-fixed-top navbar-top">
                <div class="container-fluid">
                    <table style="width: 100%">
                        <tr>
                            <td>
                                <div class="navbar-header">
                                    <button type="button" class="navbar-expand-toggle">
                                        <i class="fa fa-bars icon"></i>
                                    </button>
                                    @RenderSection("Breadcrumbs", false)
                                    <!--<button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                                        <i class="fa fa-th icon"></i>
                                    </button>-->
                                </div>
                            </td>
                            @{
                                if (Session[Constants.USER_SESSION_VARIABLE] != null && ((UserSessionVariables)Session[Constants.USER_SESSION_VARIABLE]).UserType == "admin")
                                {
                                    <td class="r-report-link r-createLogin">
                                        @Html.ActionLink("Create Login", "Index", "Login/Create")
                                    </td>

                                    <td class="r-report-link r-users">
                                        @Html.ActionLink("Users", "List", "Login")
                                    </td>
                                    <td class="r-report-link r-clients">
                                        @Html.ActionLink("Clients", "Clients", "Login")
                                    </td>
                                }
                            }
                            <td class="r-report-link r-loginLogout">
                               @Html.ActionLink("Logout", "Logout", "Login")
                               </td>
                        </tr>
                     </table>
                </div>
            </nav>
            <div class="side-menu sidebar-inverse">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="side-menu-container">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <div class=""><img src="~/img/aclara_connect_vert3.png" width="44" height="40" style="margin-left: 6px;"/></div>
                                <div class="title">Aclara</div>
                            </a>
                            <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                                <i class="fa fa-times icon"></i>
                            </button>
                        </div>
                        <ul class="nav navbar-nav">
                            @{
                                var className = Request.Path == "/" && Request.QueryString.Count == 0 ? "active" : "";
                            }
                            @Html.Action("Reports", "Dashboard")
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </div>
            <!-- Main Content -->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <footer class="app-footer">
            <div class="wrapper">
                <span class="pull-right">2.1 <a href="#"><i class="fa fa-long-arrow-up"></i></a></span> © 2015 Copyright.
            </div>
        </footer>
        <div>
            <!-- Javascript Libs -->
            <script type="text/javascript" src="~/lib/js/jquery.min.js"></script>
            <script type="text/javascript" src="~/lib/js/bootstrap.min.js"></script>
            <script type="text/javascript" src="~/lib/js/Chart.min.js"></script>
            <script type="text/javascript" src="~/lib/js/bootstrap-switch.min.js"></script>
            <script type="text/javascript" src="~/lib/js/jquery.matchHeight-min.js"></script>
            <script type="text/javascript" src="~/lib/js/jquery.dataTables.min.js"></script>
            <script type="text/javascript" src="~/lib/js/dataTables.bootstrap.min.js"></script>
            <script type="text/javascript" src="~/lib/js/select2.full.min.js"></script>
            <script type="text/javascript" src="~/lib/js/ace/ace.js"></script>
            <script type="text/javascript" src="~/lib/js/ace/mode-html.js"></script>
            <script type="text/javascript" src="~/lib/js/ace/theme-github.js"></script>
            <!-- Javascript -->
            <script type="text/javascript" src="~/js/app.js"></script>
            <script src="~/Scripts/powerbi.js"></script>
            @*<script scr="~/Scripts/powerbi.min.js"></script>*@
            <script type="text/javascript">
                window.addEventListener('DOMContentLoaded',
                    function() {
                        powerbi.init();
                    });
               </script>
        </div>
    </div>
</body>
</html>

AppLib/CE.ReportPortalWeb/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <script src="~/lib/js/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/lib/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <script type="text/javascript">
        var relativeRoot = '@Url.Content("~/")';
    </script>
</head>
<body>
@RenderBody()
</body>
</html>