AppLib/CE.AceHeadersDemoWeb/Models/LoginViewModel.cs
public class LoginViewModel
{
    public string Username { get; set; }
    public string Password { get; set; }

}

AppLib/CE.AceHeadersDemoWeb/Controllers/DemoController.cs
using System;
using System.Web.Mvc;
using System.Text;
using RestSharp;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CE.AceHeadersDemoWeb.Controllers
{
    public class DemoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel entity)
        {

            try
            {
                // setup rest client
                var client = new RestClient("https://aceapiqa.aclarax.com");

                //request
                var request = new RestRequest(Method.POST);

                //WebToken API resource endpoint
                request.Resource = "/api/v1/webtoken";

                //required security headers
                request.AddParameter("X-CE-AccessKeyId", "7320D04481A949B8AB4BB04CDD1A307E", ParameterType.HttpHeader);
                var authHeader = $"Basic {Base64Encode("7320D04481A949B8AB4BB04CDD1A307E" + ":" + "DemoBasicKey87")}";
                request.AddParameter("Authorization", authHeader, ParameterType.HttpHeader);

                //Pass the of customerId for which you
                //want to grant access to the ACE Website
                request.RequestFormat = DataFormat.Json;
                request.AddJsonBody(new { CustomerId = "993774751" });

                // execute response
                var response = client.Execute(request);

                JToken token = JObject.Parse(response.Content);

                var webToken = token.SelectToken("WebToken");

                var aceQueryStringParams = "&ClientId=" + "87"
                            + "&CustomerId=" + "993774751"
                            + "&AccountId=" + "1218337093"
                            + "&PremiseId=" + "1218337000"
                            + "&ServicePointId=" + ""
                            + "&Locale=" + "en-US"
                            + "&WebToken=" + webToken;

                //redirect to ACE Website passing the id of the
                //page you want to land on and the querystring params
                //from above in order to gain access
                var aceUrl = "https://acewebsiteqa.aclarax.com/Page?id=1&tmpl=rc&hideMenu=true" + aceQueryStringParams;
                return Redirect(aceUrl);

            }
            catch (Exception ex)
            {
                throw;
            }

        }
        private static string Base64Encode(string plainText)
        {
            var plainTextBytes = Encoding.UTF8.GetBytes(plainText);
            return Convert.ToBase64String(plainTextBytes);
        }

    }
}

AppLib/CE.AceHeadersDemoWeb/Controllers/MLGWController.cs
using System;
using System.Web.Mvc;
using System.Text;
using System.Web.ModelBinding;
using RestSharp;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CE.AceHeadersDemoWeb.Controllers
{
    public class MLGWController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel entity)
        {

            try
            {
                    //set up rest client
                    var client = new RestClient("https://aceapiqa.aclarax.com");

                    //request
                    var request = new RestRequest(Method.POST);

                    //WebToken API resource endpoint
                    request.Resource = "/api/v1/webtoken";

                    //required security headers
                    request.AddParameter("X-CE-AccessKeyId", "da7ec68a06bcf943602981fbc59dfb0a45e6", ParameterType.HttpHeader);
                    var authHeader = $"Basic {Base64Encode("da7ec68a06bcf943602981fbc59dfb0a45e6" + ":" + "MLGWBasicKey80")}";
                    request.AddParameter("Authorization", authHeader, ParameterType.HttpHeader);

                    //Pass the of customerId for which you
                    //want to grant access to the ACE Website
                    request.RequestFormat = DataFormat.Json;
                    request.AddJsonBody(new { CustomerId = "100030" });
 
                    // execute response
                    var response = client.Execute(request);

                    JToken token = JObject.Parse(response.Content);

                    var webToken = token.SelectToken("WebToken");
                     
                    var aceQueryStringParams = "&ClientId=" + "118"
                                           + "&CustomerId=" + "100030"
                                           + "&AccountId=" + "0001000301045222"
                                           + "&PremiseId=" + "1045222"
                                           + "&ServicePointId=" + ""
                                           + "&Locale=" + "en-US"
                                           + "&WebToken=" + webToken;

                    //redirect to ACE Website passing the id of the
                    //page you want to land on and the querystring params
                    //from above in order to gain access
                    var aceUrl = "https://acewebsiteqa.aclarax.com/Page?id=1&tmpl=rc&hideMenu=true" + aceQueryStringParams;
                    return Redirect(aceUrl);

            }
            catch(Exception ex)
            {
                throw ;
            }

        }
        private static string Base64Encode(string plainText)
        {
            var plainTextBytes = Encoding.UTF8.GetBytes(plainText);
            return Convert.ToBase64String(plainTextBytes);
        }

    }
}

AppLib/CE.AceHeadersDemoWeb/Views/MLGW/Index.cshtml
@model LoginViewModel

@{
    Layout = null;
}

<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/RemoteContent/118/utility.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>

<body style="margin: 0">

    <div class="container-fluid">
        <div class="row">

            <div id="bg">
                <img src="~/RemoteContent/118/bg-wind.jpg" alt="" />
            </div>

            <div id="pt1:pt_pgl15" class="container-fluid remotecontent header-wrap md-m-0">
                <div class="container">
                    <div class="row header-wrap-inner">
                        <div class="col-xs-12 col-sm-4 xs-pl-0 text-xs-center">
                            <div class="logo-wrap" name="header">
                                <a id="logoClick" class="logo">
                                    <img src="~/RemoteContent/118/mlgw_top_logo.png" />
                                </a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-8 xs-pl-0 text-xs-center text-ms-right text-sm-right text-md-right text-lg-right">
                            <div name="header" class="h__container">
                                <a class="h__link">About </a><a class="h__link">Energy Savings</a> <a class="h__link">Contact</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-dialog" style="z-index: 200">
                <div class="loginmodal-container">

                    @using (Html.BeginForm("Login", "MLGW", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <h1 style="margin-top: 5px;">Login</h1>
                        <div>

                            @if (TempData["ErrorMSG"] != null)
                            {
                                <label style="color: maroon;"> @TempData["ErrorMSG"] </label>
                                <br /><br />
                            }

                            @Html.TextBoxFor(s => s.Username, new { @placeholder = "Username" })
                            <br /> <br />
                            @Html.PasswordFor(s => s.Password, new { @placeholder = "Password" })
                            <br /> <br />
                            <button class="btn btn-danger" type="submit">Login</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>